name: Deploy
on:
  repository_dispatch:
  workflow_call:
    secrets:
      GITTER_TOKEN:
        required: true
      GITTER_ROOM_ID:
        required: true
      WEBSITE_URL:
        required: true
      GCLOUD_AUTH:
        required: true
      GCLOUD_PROJECT:
        required: true
      GCLOUD_APP:
        required: true
      CLOUDFLARE_ZONE:
        required: true
      CLOUDFLARE_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install build dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts --production
      - name: Build static files
        run: pnpm build
        env:
          FORCE_COLOR: 2
          GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
          GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
      - name: Check files changes
        id: hash
        run: ./node_modules/.bin/ssdeploy changed
        env:
          FORCE_COLOR: 2
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
      - name: Auth Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Install Google Cloud
        if: "!steps.hash.outputs.noChanges"
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy files
        if: "!steps.hash.outputs.noChanges"
        run: ./node_modules/.bin/ssdeploy deploy --verbose
        env:
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
