name: Test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  deployments: write
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install all dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build and test
        run: pnpm test
        env:
          CI: 1
          NO_CONTENT: 1
  deploy:
    name: Deploy
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
