name: Test
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install all dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build and test
        run: pnpm test
        env:
          CI: 1
          NO_CONTENT: 1
          FORCE_COLOR: 2
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -XPOST -u "${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/logux/logux.io/dispatches --data '{"event_type": "deploy"}'
